version = 0.1
[default.deploy.parameters]
stack_name = "kinesis-loader"
resolve_s3 = true
s3_prefix = "kinesis-loader"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LoaderURL=\"\""
image_repositories = []
